### ISSUE TITLE
Splash screen UI

### ISSUE THREAD

**Issue by JordiGN** [BrightCoders-Proyectos/tribo-mobile#6]
# REQUIREMENTS
Develop the splash screen
# DESIGN
Provide references to images of the design, how it looks like now, and how it should look like.

![Screen Shot 2020-12-03 at 11 34 11](https://user-images.githubusercontent.com/10423443/101066090-969b7a80-355b-11eb-98ca-1b1b9900123f.png)

# Acceptance Criteria
List all required acceptance criteria
- [ ] Splash screens show correctly

**Comment by cfcortes** [comment]
I would suggest dividing this issue into 3 issues
